### ISSUE TITLE
App crash on v2.0.0

### ISSUE THREAD

**Issue by pavikaa** [ismai117/kottie#27]
When using Kottie v2.0.0 my iOS app crashes (Android app works normally) with the following exception:
`Function 'clickable' can not be called: No function found for symbol 'androidx.compose.foundation/clickable|clickable@androidx.compose.ui.Modifier(androidx.compose.foundation.interaction.MutableInteractionSource;androidx.compose.foundation.Indication?;kotlin.Boolean;kotlin.String?;androidx.compose.ui.semantics.Role?;kotlin.Function0<kotlin.Unit>){}[0]'`

Upon investigation, the **compose-plugin 1.7.0-beta02** could be causing the problem.

Temporary solution:
Downgrade Kottie to v1.9.6

**Comment by typ-AhmedSleem** [comment]
Yeah. It happens with me also

**Comment by matteogazzato** [comment]
Not happening with [1.9.6](https://github.com/ismai117/kottie/releases/tag/1.9.6).
This is due to compose-plugin upgrade to 1.7.0-beta02, with v1.6.11 it is working fine.

There's is an [issue](https://youtrack.jetbrains.com/issue/CMP-6668) currently open and they are reviewing the PR.

Possibly it is fixing soon.

**Comment by ismai117** [comment]
I've released a new version 2.0.1; upgraded kotlin version to 2.0.21 & compose-plugin to 1.7.0
